### ISSUE TITLE
Version 1.0.1 is not backward compatible

### ISSUE THREAD

**Issue by RickPoleshuck** [xclud/window_location_href#2]
Thank you for this package. I hope you accept my criticism as constructive.

When a package is not backward compatible, you should change the first number of the version. Take a look at this website: https://semver.org/

**Comment by xclud** [comment]
Hi,
Thanks for the feedback.

This change was not intended for publishing to pub.dev. It was a work-in-progress accidentally published by the CI.

This should be fixed now. I apologize any inconveniences.
